### ISSUE TITLE
http://example.org/inMemory	http://example.org/2020/

### ISSUE THREAD

**Issue by scenaristeur** [jeff-zucker/sparql-fiddle#1]
Hi @jeff-zucker playing a little bit with https://jeff-zucker.github.io/sparql-fiddle/ for POD querying, it seems that some "http://example.org/inMemory	http://example.org/2020/" appear in the result instead of the real attributes of the resource, is it a bug or am i doing something wrong ? 
not tested yet the js api

![Screenshot_2020-02-13 SPARQL Fiddle(2)](https://user-images.githubusercontent.com/4020744/74451985-b9e82280-4e80-11ea-83ce-6617258c779d.png)

**Comment by jeff-zucker** [comment]
That is how SPARQL-Fiddle portrays the subject of the query when it is an entirely in-memory query.  Perhaps I shouldn't do it that way, but that's how it works now.  So not a problem on your end.  I will probably be replacing most of SPARQL-Fiddle with my rdf-easy which has the programming API but not yet the online playground.  It does not add the bogus example.org thing.

**Comment by jeff-zucker** [comment]
P.S. If you are going to develop in SPARQL or use it in an app, I recommend rdf-easy - the name is misleading, it's actually all about SPARQL.

**Comment by scenaristeur** [comment]
Ok, great. 
Thxs, I'll take a look at rdf-easy. 
You really are a STM ! 
-> a Solid Tools Master ! 👍💪😉
