### ISSUE TITLE
Error: $rdf is not defined

### ISSUE THREAD

**Issue by renyuneyun** [jeff-zucker/sparql-fiddle#3]
I'm trying to use this app to perform SPARQL query against a Solid resource.
I typed my resource URI, and entered the SPARQL query text. Hitting "run" did not work.
Then I copied the resource content (Turtle). Hitting "run" also did not work.
Opening the console gives me this error (repeatedly):

```
ReferenceError: $rdf is not defined
    run https://jeff-zucker.github.io/sparql-fiddle/sparql-fiddle.js:199
    run https://jeff-zucker.github.io/sparql-fiddle/sparql-fiddle.js:197
    run https://jeff-zucker.github.io/sparql-fiddle/:125
    onclick https://jeff-zucker.github.io/sparql-fiddle/:1
[sparql-fiddle:127:27](https://jeff-zucker.github.io/sparql-fiddle/)
```

**Comment by jeff-zucker** [comment]
Sorry, @renyuneyun  this library is quite stale and I have not had time to update it.  You have spurred me to act, though.  I will be releasing an entirely new version of the library soon.  Chances are , you can resolve that particular issue by importing rdflib in a script prior to importing sparql-fiddle.

**Comment by renyuneyun** [comment]
Thanks, Jeff. I'll try that. It's really interesting that this is the only app I found that allows to test SPARQL queries for Solid resources...
Of course building my own app would be an option, but it's not as convenient...

**Comment by jeff-zucker** [comment]
@renyuneyun - I have a new improved SPARQL access library that allows you to choose either rdflib or comunica and supports replaceable query parameters.  Please check out  the [sol-sparql web component](https://solidos.github.io/solid-web-components/documentation/sol-sparql.html) and let me know what you think.
